version: "3.7"

services:
  trust_network_back:
    build: ./
    command: >
      sh -c "python trust_network/manage.py migrate &&
             python trust_network/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/app/
    ports:
      - 8080:8000
  trust_network_db:
    image: postgres:12
    volumes:
      - trust_network_postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev
    ports:
      - 5432:5432

volumes:
  trust_network_postgres_data: